import type { Supplier } from "./model";

export const suppliers: Supplier[] = [
  {
    id: "1",
    name: "УралФрут",
    category: "Овощи и фрукты",
    city: "Екатеринбург",
    minOrder: 15000,
    delivery: "1 день",
    certificates: ["ГОСТ", "ХАССП"],
    rating: 4.8,
    website: "#",
  },
  {
    id: "2",
    name: "Мясной Двор",
    category: "Мясо и птица",
    city: "Екатеринбург",
    minOrder: 30000,
    delivery: "1-2 дня",
    certificates: ["Меркурий"],
    rating: 4.6,
    website: "#",
  },
  {
    id: "3",
    name: "MilkTrade",
    category: "Молочная продукция",
    city: "Москва",
    minOrder: 25000,
    delivery: "2 дня",
    certificates: ["ГОСТ"],
    rating: 4.7,
    website: "#",
  },
  {
    id: "4",
    name: "PackPro",
    category: "Упаковка",
    city: "Екатеринбург",
    minOrder: 5000,
    delivery: "Самовывоз / доставка",
    certificates: ["ISO 9001"],
    rating: 4.5,
    website: "#",
  },
  {
    id: "5",
    name: "СибирьФиш",
    category: "Рыба и морепродукты",
    city: "Новосибирск",
    minOrder: 40000,
    delivery: "2-4 дня",
    certificates: ["Меркурий", "ХАССП"],
    rating: 4.4,
    website: "#",
  },
  {
    id: "6",
    name: "УралБакалея",
    category: "Бакалея",
    city: "Челябинск",
    minOrder: 10000,
    delivery: "1-3 дня",
    rating: 4.3,
    website: "#",
  },
];